version: 2
updates:
  - package-ecosystem: 'docker'
    directory: '/'
    commit-message:
      prefix: 'feat: '
    schedule:
      interval: 'weekly'
    groups:
      dependencies:
        patterns:
          - '*'
    labels: []

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      dependencies:
        patterns:
          - '*'
    labels: []
